### ISSUE TITLE
Nedostaje prikaz opisa predmeta

### ISSUE THREAD

**Issue by edoimamovic** [SoftverInzenjeringETFSA/SI2016_TIM6#1]
Commit ID: 9884bde73594097a44369c86dced1565feb13f8e
Komponenta: PredmetDetalji.js
Opis problema: Prema SRS-u, atribut predmeta koji treba dodatno prikazati je i opis predmeta, što podrazumijeva kratki tekst o tome šta se na predmetu izučava. Trenutno se opis predmeta ne prikazuje, odnosno prikazuju se samo podaci o upisanoj ocjeni, predmetnom nastavniku i prosječnoj ocjeni.

Koraci za reprodukciju: 
1. Login kao student koji pohađa neke predmete, naprimjer korisnik iz baze mesa1.
2. Otvaranje podstranice "Predmeti"
3. Pregled nekog konkretnog predmeta

**Comment by sbecirovic** [comment]
Ispravljeno
