### ISSUE TITLE
Nesklađenost SRS-a i prikazivanja termina ispita na aplikaciji

### ISSUE THREAD

**Issue by simamovic3** [SoftverInzenjeringETFSA/SI2016_TIM6#10]
Commit ID: 7f7d8db

Komponenta: IspitRepository.java

Opis problema: U SRS-u piše "Studentima će biti prikazani samo oni termini koji su aktivni u datom periodu, što smanjuje mogućnost zabune i prijave na pogrešni termin.", a prikazuju se svi (i aktivni i neaktivni). I na strani 20 piše- preduslov za prikazivanje "termin je aktivan". Aktivni ispit znači ispit kojem nije istekao rok za prijavu.

Koraci za reprodukciju:

Ulogovati se kao neki korisnik za kojeg ima ispit na koji se može prijaviti - naprimjer mesa1 iz postavljenog dumpa.

Otići na podstranicu "Termini ispita"

Očekivani izlaz: Samo aktivni termini
Dobijeni izlaz: I aktivni i neaktivni

![image](https://cloud.githubusercontent.com/assets/17410187/26765031/77ea1178-4973-11e7-8199-9aafa45bcd5e.png)

**Comment by sbecirovic** [comment]
S obzirom da je rok prijave do 17.06.2017. termin je validan. Ne vidimo u čemu je problem.

**Comment by EdinBegic** [comment]
Ispravljeno commit-om f8be1087603116640716fe8f89c2fcdf2097d51c
