### ISSUE TITLE
Moguće je unijeti lozinku od 5 karaktera

### ISSUE THREAD

**Issue by ekalac1** [SoftverInzenjeringETFSA/SI2016_TIM6#11]
**Commit ID** : 7d97e74
**Komponenta** :  StudentController.java
**Opis problema**: U SRS-u je navedeno da će lozinka imati dužinu mininalno 6 karaktera, a lozinku je moguće promjeniti tako da ima 5 karaktera. 

**Koraci za reprodukciju**: 
1. Logovati se kao bilo koji korisnik, npr mesa1
2. Iz izbornika odabrati Profil
3. Na dnu stranice profil, u polja novi password unijeti lozinku od 5 karaktera, a u polje stari password unijeti trenutni password. 
4. Pritisnuti dugme Promjeni šifru. 

![image](https://cloud.githubusercontent.com/assets/17406285/26764881/3765170e-4970-11e7-800f-66cef3d1f42b.png)

**Očekivani izlaz**: Poruka o neuspjeloj promjeni lozinke. 
**Dobijeni izlaz**: Uspješna promjena lozinke.

**Comment by ebeus** [comment]
Ispravljeno commitom 061c2a983c62b668a798354040c62383eac546a1
