### ISSUE TITLE
UI: ne vidi se uneseni tekst od ikone

### ISSUE THREAD

**Issue by edoimamovic** [SoftverInzenjeringETFSA/SI2016_TIM6#14]
**Commit ID:** 7d97e74718fd846a197561fdb2139f3580e4f26b
**Komponenta:** LoginPage.js
**Opis problema:** Ukoliko je username dovoljno dug, ikona u textboxu za username na login stranici prekriva par slova.
<img src="http://i.imgur.com/M8o1w57.png" />

**Comment by jbajramovi1** [comment]
Ispravljeno commitom 5d4c58a
