### ISSUE TITLE
Nekonzistentan izgled login stranice u Edge-u

### ISSUE THREAD

**Issue by simamovic3** [SoftverInzenjeringETFSA/SI2016_TIM6#15]
Commit ID: 7d97e74
Komponenta : profil.js
Opis problema: Kada se aplikacija pokrene preko Edge-a razlikuje se izgled u odnosu na ostale browsere.
Koraci za reprodukciju:
Pokrenuti aplikaciju preko Edge-a
Logovati se kao bilo koji korisnik, npr mesa1
Iz izbornika odabrati Profil

![image](https://cloud.githubusercontent.com/assets/17410187/26765301/a5b77c3e-4979-11e7-92dc-6d6e2a9fd1b5.png)

Očekivani izlaz: Postoje linije koje podvače korisničke podatke na profilu.
(Ovako je u ostalim browserima)
![image](https://cloud.githubusercontent.com/assets/17410187/26765327/11e695f2-497a-11e7-9f31-ffb08e65638c.png)

Dobijeni izlaz: Linije koje inače podvlače korisničke podatke na ostalim browserima, u ovom slučaju su pomjerene sa desne strane.

**Comment by jbajramovi1** [comment]
Ispravljeno commitom 69afe8e
