### ISSUE TITLE
Nedostaje provjera da li je korisnik siguran kod odjave ispita

### ISSUE THREAD

**Issue by simamovic3** [SoftverInzenjeringETFSA/SI2016_TIM6#17]
Commit ID: 739167c
Komponenta: Ispiti.js
Opis problema: Ukoliko korisnik klikne na odjavu ispitnog termina, prema SRS-u  je potrebno da se omogući neka vrsta provjere da li je korisnik siguran u odjavu ili je slučajno kliknuo na nju. Trenutno nedostaje takva provjera.
![image](https://cloud.githubusercontent.com/assets/17410187/26765492/5763956e-497d-11e7-9085-ad1d3ba897aa.png)

Koraci za reprodukciju:

Ulogovati se kao neki korisnik za kojeg ima ispit na koji se može prijaviti - naprimjer mesa1 iz postavljenog dumpa.

Otići na podstranicu "Termini ispita"

Nakon što su se učitali ispiti koji se mogu prijaviti ili odjaviti, kliknuti na odjavu sa nekog ispita.

Očekivani izlaz: Provjera da li se radi o grešci.
Dobijeni izlaz: /

**Comment by nejra5** [comment]
Ispravljeno.
