### ISSUE TITLE
Nedostaje provjera kapaciteta termina ispita

### ISSUE THREAD

**Issue by ekalac1** [SoftverInzenjeringETFSA/SI2016_TIM6#2]
**Komponenta** : IspitRepository.java
**Commit ID** : 9884bde

**Opis problema**: U SRS-u je navedeno da će se prilikom prikazivanja termina ispita prikazivati samo oni termini ispita koji nisu popunjeni, ali nigdje u projektu se ne bilježi podatak koji bi ukazao na kapacitet termina ispita, nego se samo dobavljaju svi ispiti na koje student nije prijavljen.

**Comment by sbecirovic** [comment]
Ispravljeno.
