### ISSUE TITLE
Password hash algoritam

### ISSUE THREAD

**Issue by himamovic1** [SoftverInzenjeringETFSA/SI2016_TIM6#3]
**Komponenta:** _StudentController.java_ (metoda _updatePassword_), _StudentService.java_ (metoda _getMD5_)
**commitID:**  ba4f82b

**Opis problema:** U SRS-u (_poglavlje 3.4._)  stoji da će se lozinke korisnika biti hash-irane _SHA-2_ algoritmom, no implementirano je hash-iranje _MD5_ algoritmom. Što pored neslaganja sa SRS-om predstavlja i sigurnosni propust.

SRS:
![d66418d78ba63b190014f81a279b7053](https://cloud.githubusercontent.com/assets/17404829/26757749/e20285a6-48c7-11e7-9cab-39ab8651fe05.jpg)

**Comment by sbecirovic** [comment]
Ispravljeno.
