### ISSUE TITLE
Nekompatibilnost ER dijagrama i baze

### ISSUE THREAD

**Issue by simamovic3** [SoftverInzenjeringETFSA/SI2016_TIM6#5]
Komponenta: tim6.sql

Commit ID: 7d97e74

Opis problema: Skripta za bazu sastoji se od jedne tabele više nego što je predviđeno ER dijagramom koji se nalazi u SRS-u (tabela obavjestenja). Student u bazi ima: spol, adresa, telefon, username a na ERD-u nema. U tabeli prijava u bazi ima id, dok na ERD-u imaju samo KorisnikId i IspitId. Razlikuje se i tip(tj opseg) u tabeli student kod: ime, prezime, mjesto, zatim tabeli profesor: ime, prezime, u ERD-u je rezervisano 30 znakova, dok je u bazi 256. Također svi id-evi u ERD-u imaju pomenuti opseg 10 znakova, dok u bazi imaju 11.

**Comment by emir16949** [comment]
Bug zahtijeva promjenu dokumentacije, nisam pronašao labelu documentation.
