### ISSUE TITLE
Sigurnosni propust - prolazi nevalidna prijava ispita predmeta direktno na backend

### ISSUE THREAD

**Issue by edoimamovic** [SoftverInzenjeringETFSA/SI2016_TIM6#6]
**Commit ID:** 7d97e74718fd846a197561fdb2139f3580e4f26b
**Komponenta:** PrijavaService.java
**Opis problema:** Ukoliko se POST zahtjev uputi direktno ka serveru na /prijave/prijavi, moguće je u bazu unijeti prijavu ispita koji je otvoren ali ga student ne pohađa, što je u suprotnosti sa preduslovima iz stavke 3.2.5.1. u SRS-u.

Koraci za reprodukciju:
1. Poslati POST zahtjev na endpoint http://localhost:8080/prijava sa bodyjem {"username":"mesa1", "password":"password"}. Ovdje se podrazumijeva da se radi sa dumpom baze koji je objavljen na repozitoriju; također, za ovaj primjer je korištena aplikacija Postman za slanje HTTP zahtjeva, mada može poslužiti i bilo koja druga slična:

<img src="http://i.imgur.com/UT0wo7W.png">

2. Iz headera odgovora iskopirati sadržaj polja Authorization:

<img src="http://i.imgur.com/32oBWco.png">

3. Napraviti novi POST zahtjev prema endpointu http://localhost:8080/prijave/prijava.
Postaviti parametre student=1, ispit=18, model_attribute="prijava"; dakle, šaljemo POST zahtjev sa URL-om http://localhost:8080/prijave/prijavi?student=1&ispit=18&model_attribute="prijava".
Prije slanja zahtjeva, u header dodati polje Authorization sa vrijednošću iskopiranom pod 2., uz Content-Type=multipart/form-data; boundary=&.

U bazi možemo provjeriti da je ispit s ID-om 18 vezan za predmet s ID-om 20, a korisnik s ID-om 1 (mesa1) ne pohađa predmet 20, što znači da ovo ne bi trebalo proći.

<img src="http://i.imgur.com/WmX8MAK.png">

4. Nakon što smo poslali prethodni zahtjev, možemo vidjeti u bazi da je zaista uspješno dodana prijava na ispit koji se ne pohađa.

<img src="http://i.imgur.com/bj7nZE1.png">

**Očekivani izlaz**: HTTP status koji ukazuje na grešku, nepromijenjena baza.
**Dobijeni izlaz**: HTTP status OK, dodana prijava u bazi.

**Comment by EdinBegic** [comment]
Ispravljeno.
