### ISSUE TITLE
Nedostaje poruka greške kod neuspješne prijave i odjave ispita

### ISSUE THREAD

**Issue by edoimamovic** [SoftverInzenjeringETFSA/SI2016_TIM6#7]
**Commit ID:** 739167c03702b649b589cbb9c70fd6ebb748d8c9
**Komponenta:** Ispiti.js
**Opis problema:** Ukoliko odjava/prijava ispitnog termina ne prođe uspješno, prema SRS-u (3.2.5.2. izlazne vrijednosti) je potrebno ispisati poruku o grešci. Trenutno nedostaje takva poruka.

Koraci za reprodukciju:
1. Ulogovati se kao neki korisnik za kojeg ima ispit na koji se može prijaviti - naprimjer mesa1 iz postavljenog dumpa.

2. Otići na podstranicu "Termini ispita"

3. Nakon što su se učitali ispiti koji se mogu prijaviti ili odjaviti (ovdje je to samo Inženjerska fizika 1), zaustaviti pokrenuti server kako bi se jednostavno izazvala greška.

3. Kada je server stao sa radom, pritisnuti dugme "Prijavi" pored ispitnog termina.
Ništa se ne dešava: http://i.imgur.com/dX9SLL6.png

**Očekivani izlaz**: Poruka o grešci
**Dobijeni izlaz**: /

**Comment by ebeus** [comment]
Ne može se garantovati kako će se aplikacija ponašati nakon što stane server.

**Comment by edoimamovic** [comment]
Na svaki poslan zahtjev sa frontenda se može dodati i predvidivo ponašanje u slučaju odbijenog requesta, odnosno nedostatka odgovora, kao što je uostalom urađeno ukoliko se navigira na podmeni Obavještenja ili Predmeti.

**Comment by EdinBegic** [comment]
Kako se deploy radi u vidu jedne web aplikacije, kreirat će se .war file preko kojeg će ista pokrenuti, odnosno nije moguće zasebno pokrenuti frontend i backend, te time nije moguće izazvati ovaj bug jer bi dovelo do krahiranja cijele aplikacije
