### ISSUE TITLE
Ispisivanje obavještenja iz neaktulnog semestra

### ISSUE THREAD

**Issue by ekalac1** [SoftverInzenjeringETFSA/SI2016_TIM6#9]
**Commit ID** : 7d97e74
**Komponenta** : ObavjestenjeRepository.java

**Opis problema**: U SRS-u je navedeno se korisniku prikazuju obavještenja iz tekućeg semestra, a prikazuju se obavještenja iz svih predmeta iz kojih korisnik nema upisanu ocjenu.  

**Koraci za reprodukciju**: 
1. U bazi, u tabeli pohadjanja promjeniti ocjenu iz predmeta sa id 3 sa 9 na null, za id korisnika 2.
2. Bilo kom obavještenju u tabeli obavještenja promjeniti id predmeta na 3, osim obavještenja kojem je id 6. 
3. Ulogovati se kao korisnik silvana1
4. U obavještenjima će se prikazati obavještenja iz predmeta koji su u dva različita semestra. 

(uglavnom, obavještenja se prikazuju po neupisanim ocjenama, a ne po trenutnom semestru)

![image](https://cloud.githubusercontent.com/assets/17406285/26764766/c1e96428-496d-11e7-9328-07c6b1d555b4.png)
 
![image](https://cloud.githubusercontent.com/assets/17406285/26764783/dea54d98-496d-11e7-834c-bf8754c354b7.png)

**Očekivani izlaz**: Obavještenja iz predmeta u tekućem semestru. 
**Dobijeni izlaz**: Obavještenja iz predmeta u kojima ocjena nije upisana.

**Comment by EdinBegic** [comment]
Ispravljeno.
